title: Quincy Ryan
email: qmryan@ucdavis.edu
description: "Personal academic website"
github_username: Qu1ncyRy4n

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark" 

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

include: ["_pages"]

author:
  name: "Quincy Ryan"
  bio: ""
  location: "Davis, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Qu1ncyRy4n"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:qmryan@ucdavis.edu"